language: node_js

services:
  - docker

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: unit tests
      # before_script: docker-compose p -f integration-tests/docker-compose.yml up
      script: npm run test:unit:ci
    - stage: integration tests
      script: npm run test:integration:ci
      # after_script: npm run test:coverage