language: node_js

services:
  - docker

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: test
      before_script: docker-compose up -f integration-tests/docker-compose.yml
      script: npm run test:unit
      script: npm run test:integration
      after_script: npm run test:coverage