language: node_js

services:
  - docker

cache:
  directories:
    - node_modules
before_install:
  - docker-compose up -f integration-tests/docker-compose.yml

jobs:
  include:
    - stage: test
      script: npm run test:unit
      script: npm run test:integration
      after_script: npm run test:coverage